# Generated by Django 5.1.5 on 2025-01-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_rename_table_id_order_table_remove_food_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], default='P', max_length=1),
        ),
    ]
